import { Stack, Button } from '@mui/material'
import { count } from 'console'
import Head from 'next/head'
import Image from 'next/image'
import { useSelector } from 'react-redux'
import { increment, decrement, incrementByAmount } from '../store/slices/counterSlice'
import { RootState, useAppDispatch } from '../store/store'
import styles from '../styles/Home.module.css'
import Componets from '../components/login-btn'
import Signin from '../pages/signin'
import { useEffect, useState } from 'react'
import Header from '../layout/Header/Header'
import Dashboard from './dashboard/dashboard'
import { useSession } from 'next-auth/react'
import Link from 'next/link'
import router from 'next/router'

export default function Home() {

 
  const count= useSelector((state: RootState)=> state.counter.value);
  // const dispatch = useDispatch()
  const { data: session } = useSession()
  const dispatch = useAppDispatch()
  const [numb, setNumb] = useState(0)
  // useEffect(() => {
  //   if(session){
  //     router.push('/dashboard/dashboard')
  //   }
  // },)
  // useEffect(() => {
  //   console.log('App useEffect numb' + numb)
  // },[numb])
  // const test = () => {
  //   <Link href={'/dashboard/dashboard'}></Link>
  // }
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Dashboard/> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        

        {/* <h1 className="text-3xl font-bold underline">
             Hello world! Tailwind
        </h1> */}

       <Button onClick={() => (setNumb(prev => prev+1))}  variant="contained">{numb}</Button>

        <h1>the value of counter is {count}</h1>
      <Stack spacing={2} direction="row"> 
      <Button color="success" onClick={() => dispatch(increment())} variant="contained">+</Button>
      <Button color="error" onClick={() => dispatch(decrement())} variant="contained">-</Button>
      <Button onClick={() => dispatch(incrementByAmount(2))} variant="contained">+2</Button>

    </Stack><br/>
    <Componets/>

      </main>

    </div>
  )
}
